### ISSUE TITLE
undefined symbol: swift_register_ast_chan

### ISSUE THREAD

**Issue by chrootlogin** [dOpensource/app_swift#5]
When I try to load the compiled app_swift.so, then I get the following error:
```
[2020-01-21 17:50:11] ERROR[28502] loader.c: Error loading module 'app_swift': /usr/lib/asterisk/modules/app_swift.so: undefined symbol: swift_register_ast_chan
```

Asterisk version: Asterisk 16.2.1~dfsg-1+deb10u1
Swift version: Cepstral Swift v6.1.5
Plattform: Raspberry Pi 3 ARMv7l
OS: Raspbian Buster

**Comment by patrickdexter** [comment]
Only the Cepstral 8kHz Telephony voices will work and those are available for x86 chipsets. Swift for the Raspberry Pi is not supported with app_swift.

**Comment by cam100in1** [comment]
I am also trying to get app_swift loaded. And it is possible, when the codeline with "swift_register_ast_chan" is commented out. So i took a look into the  libswift.so.6 (arm)
And "nm -gD libswift.so | grep register" shows, that this function is not in the lib !! I tested the x86 and the arm version. Both with the same result. So app_swift.c is calling a nonexisting libfunction. I don't have the SDK documentation, but there must be a other way to register the channel.
I also got swift and app_swift go working and i can call a extention to get a spoken sentence German). But i am not shure, that app_swift will work under all conditions w/o registering a channel.
So please check the code. It is NOT the wrong plattform. I think there is a header vs. lib missmatch somehow...

regards

**Comment by patrickdexter** [comment]
What is the output of 

swift -V

**Comment by cam100in1** [comment]
Cepstral Swift v6.1.5, March 2017

Default Voice:  Katrin               v6.1.5
Language:       German               v6.1.5
Lexicon:        German               v6.1.5

Product:        Cepstral for Raspberry Pi license was found.

Concurrency:    1 Port(s) Registered
                0 Port(s) In Use

Distribution:   Saving audio to a file is enabled.
                Distribution of audio is PROHIBITED.

Copyright (C) 2000-2017, Cepstral LLC.

**Comment by patrickdexter** [comment]
> Only the Cepstral 8kHz Telephony voices will work and those are available for x86 chipsets. Swift for the Raspberry Pi is not supported with app_swift.

As stated before app_swift does not work with the ARM voices. Only the 8kHz Telephony voices will work with app_swift. 

https://www.cepstral.com/en/telephony/download/?os=linux&refpage=linux

**Comment by cam100in1** [comment]
This is under "personal" downloads ...
https://www.cepstral.com/downloads/installers/linuxARM/Cepstral_Katrin_arm-linux_6.1.5.tar.gz

**Comment by patrickdexter** [comment]
Yeah I don't know how to be more clear about this. The Personal voices DO NOT work with app_swift. Only the Telephony Voices work with app_swift.

**Comment by cam100in1** [comment]
BTW. When playing the voice, i am getting tones of this :)
But voice is ok....
app_swift.c:186 swift_generator_running: FRACK!, Failed assertion bad magic number 0xe for object 0xb4017238 (0)

**Comment by cam100in1** [comment]
Calling swift with system() also working. I can live without app_swift.....

exten => 731,3,System(rm -rf /tmp/test.wav)
exten => 731,4,System(/opt/swift/bin/swift -n Matthias -o /tmp/test.wav -p audio/sampling-rate=8000,audio/channels=1 "Nach dem Pieptone bitte die ersten drei Buchstaben des Namens eingeben, den Sie anrufen wollen.")
exten => 731,5,Playback(/tmp/test)
exten => 731,6,Goto(731,8)
;# // exten => 412,n,Swift("At the beep enter the first three letters of the name of the person you wish to contact.")
exten => 731,7,Swift("Nach dem Piepton bitte die ersten drei Buchstaben des Namens eingeben, den Sie anrufen wollen.")

**Comment by cam100in1** [comment]
Ok, the needed function ist "ONLY in the "telephony" version.... That is the differnce

**Comment by devopsec** [comment]
As @patrickdexter mentioned app_swift only supports the telephony voices.  
If Cepstral wants us to add support for more voices they will let us know, until then I am closing this issue out.
